import type {
  PerformanceHubAgendaItem,
  PerformanceHubAvaliacao,
  PerformanceHubStaffOption,
  PerformanceHubTimeSlug,
} from "./academyPerformanceHubTypes";

export const PERFORMANCE_HUB_STAFF_POR_TIME: Record<
  PerformanceHubTimeSlug,
  PerformanceHubStaffOption[]
> = {
  game_presenter: [
    { value: "ana", label: "Ana Beatriz Silva", turno: "Manhã" },
    { value: "rafael", label: "Rafael Costa", turno: "Tarde" },
    { value: "juliana", label: "Juliana Ferreira", turno: "Noite" },
    { value: "fernando", label: "Fernando Rocha", turno: "Manhã" },
    { value: "camila", label: "Camila Duarte", turno: "Tarde" },
  ],
  shuffler: [
    { value: "diego", label: "Diego Santana", turno: "Tarde" },
    { value: "marcos", label: "Marcos Vieira", turno: "Noite" },
  ],
};

export const PERFORMANCE_HUB_AVALIACOES_MOCK: PerformanceHubAvaliacao[] = [
  {
    id: "1",
    data: "24/06/2026",
    time: "game_presenter",
    avaliadoNome: "Ana Beatriz Silva",
    avaliadorNome: "Carlos Mendes",
    status: "concluida",
    notaTotal: 8.8,
    notaImagem: 9,
    notaComunicacao: 8.5,
    notaMesa: 9,
    videoUrl: "#",
  },
  {
    id: "2",
    data: "22/06/2026",
    time: "game_presenter",
    avaliadoNome: "Rafael Costa",
    avaliadorNome: "Mariana Lima",
    status: "em_analise",
    notaTotal: 7.5,
    notaImagem: 7.5,
    notaComunicacao: 7,
    notaMesa: 8,
    videoUrl: "#",
  },
  {
    id: "3",
    data: "18/06/2026",
    time: "game_presenter",
    avaliadoNome: "Juliana Ferreira",
    avaliadorNome: "Carlos Mendes",
    status: "feedback",
    notaTotal: 8.7,
    notaImagem: 8.5,
    notaComunicacao: 9,
    notaMesa: 8.5,
    videoUrl: "#",
  },
  {
    id: "4",
    data: "10/06/2026",
    time: "game_presenter",
    avaliadoNome: "Fernando Rocha",
    avaliadorNome: "Mariana Lima",
    status: "pendente",
    notaTotal: null,
    notaImagem: null,
    notaComunicacao: null,
    notaMesa: null,
    videoUrl: null,
  },
  {
    id: "5",
    data: "20/06/2026",
    time: "shuffler",
    avaliadoNome: "Diego Santana",
    avaliadorNome: "Carlos Mendes",
    status: "concluida",
    notaTotal: 8.3,
    notaImagem: 8,
    notaComunicacao: 8.5,
    notaMesa: 8.5,
    videoUrl: "#",
  },
];

export const PERFORMANCE_HUB_AGENDA_MOCK: PerformanceHubAgendaItem[] = [
  {
    id: "a1",
    time: "game_presenter",
    nome: "Fernando Rocha",
    goLive: "12/03/2026",
    turno: "Manhã",
    realizadas: 3,
    pendentes: 1,
  },
  {
    id: "a2",
    time: "game_presenter",
    nome: "Camila Duarte",
    goLive: "22/01/2026",
    turno: "Tarde",
    realizadas: 5,
    pendentes: 2,
  },
  {
    id: "a3",
    time: "game_presenter",
    nome: "Bruno Nakamura",
    goLive: "05/06/2026",
    turno: "Noite",
    realizadas: 1,
    pendentes: 1,
  },
  {
    id: "a4",
    time: "shuffler",
    nome: "Diego Santana",
    goLive: "08/02/2026",
    turno: "Tarde",
    realizadas: 2,
    pendentes: 1,
  },
];
