import type {
  PerformanceHubAgendaItem,
  PerformanceHubAvaliacao,
  PerformanceHubStaffOption,
  PerformanceHubTimeSlug,
} from "./academyPerformanceHubTypes";

export const PERFORMANCE_HUB_STAFF_POR_TIME: Record<
  PerformanceHubTimeSlug,
  PerformanceHubStaffOption[]
> = {
  game_presenter: [
    { value: "ana", label: "Ana Beatriz Silva", turno: "Manhã" },
    { value: "rafael", label: "Rafael Costa", turno: "Tarde" },
    { value: "juliana", label: "Juliana Ferreira", turno: "Noite" },
    { value: "fernando", label: "Fernando Rocha", turno: "Manhã" },
    { value: "camila", label: "Camila Duarte", turno: "Tarde" },
  ],
  shuffler: [
    { value: "diego", label: "Diego Santana", turno: "Tarde" },
    { value: "marcos", label: "Marcos Vieira", turno: "Noite" },
  ],
};

export const PERFORMANCE_HUB_AVALIACOES_MOCK: PerformanceHubAvaliacao[] = [
  {
    id: "1",
    data: "24/06/2026",
    time: "game_presenter",
    avaliadoNome: "Ana Beatriz Silva",
    avaliadorNome: "Carlos Mendes",
    status: "concluida",
    tipoAvaliacao: "performance_coach",
    turno: "Manhã",
    estudioId: "sports_club",
    jogo: "baccarat",
    mesaId: "101",
    pontosFortes: "Excelente comunicação com novos jogadores e postura impecável.",
    pontosDesenvolver: "Aumentar ritmo nas trocas de dealer em mesas mais movimentadas.",
    notaTotal: 8.8,
    notaImagem: 9,
    notaComunicacao: 8.5,
    notaMesa: 9,
    notaProcedimentos: null,
    videoUrl: "#",
    videoNome: "ana-beatriz-24062026.mp4",
  },
  {
    id: "2",
    data: "22/06/2026",
    time: "game_presenter",
    avaliadoNome: "Rafael Costa",
    avaliadorNome: "Mariana Lima",
    status: "em_analise",
    tipoAvaliacao: "performance_coach",
    turno: "Tarde",
    estudioId: "sports_club",
    jogo: "roleta",
    mesaId: "201",
    pontosFortes: null,
    pontosDesenvolver: null,
    notaTotal: 7.5,
    notaImagem: 7.5,
    notaComunicacao: 7,
    notaMesa: 8,
    notaProcedimentos: null,
    videoUrl: "#",
    videoNome: "rafael-costa-22062026.mp4",
  },
  {
    id: "3",
    data: "18/06/2026",
    time: "game_presenter",
    avaliadoNome: "Juliana Ferreira",
    avaliadorNome: "Carlos Mendes",
    status: "feedback",
    tipoAvaliacao: "performance_coach",
    turno: "Noite",
    estudioId: "blaze_dedicado",
    jogo: "blackjack",
    mesaId: "310",
    pontosFortes: "Domínio técnico das regras e energia positiva na mesa.",
    pontosDesenvolver: "Uniformizar volume de voz entre abertura e fechamento do jogo.",
    notaTotal: 8.7,
    notaImagem: 8.5,
    notaComunicacao: 9,
    notaMesa: 8.5,
    notaProcedimentos: null,
    videoUrl: "#",
    videoNome: "juliana-18062026.mp4",
  },
  {
    id: "4",
    data: "10/06/2026",
    time: "game_presenter",
    avaliadoNome: "Fernando Rocha",
    avaliadorNome: "Mariana Lima",
    status: "pendente",
    tipoAvaliacao: null,
    turno: null,
    estudioId: null,
    jogo: null,
    mesaId: null,
    pontosFortes: null,
    pontosDesenvolver: null,
    notaTotal: null,
    notaImagem: null,
    notaComunicacao: null,
    notaMesa: null,
    notaProcedimentos: null,
    videoUrl: null,
    videoNome: null,
  },
  {
    id: "5",
    data: "20/06/2026",
    time: "shuffler",
    avaliadoNome: "Diego Santana",
    avaliadorNome: "Carlos Mendes",
    status: "concluida",
    tipoAvaliacao: "performance_coach",
    turno: "Tarde",
    estudioId: "sports_club",
    jogo: null,
    mesaId: null,
    pontosFortes: "Agilidade e precisão no embaralhamento.",
    pontosDesenvolver: "Manter contato visual com a câmera durante procedimentos.",
    notaTotal: 8.3,
    notaImagem: 8,
    notaComunicacao: 8.5,
    notaMesa: null,
    notaProcedimentos: 8.5,
    videoUrl: "#",
    videoNome: "diego-20062026.mp4",
  },
  {
    id: "6",
    data: "15/05/2026",
    time: "game_presenter",
    avaliadoNome: "Diego Santana",
    avaliadorNome: "Mariana Lima",
    status: "concluida",
    tipoAvaliacao: "performance_coach",
    turno: "Tarde",
    estudioId: "sports_club",
    jogo: "blackjack",
    mesaId: "301",
    pontosFortes: "Boa energia na mesa antes da transição de cargo.",
    pontosDesenvolver: "Aprimorar anúncio de estatísticas.",
    notaTotal: 7.9,
    notaImagem: 8,
    notaComunicacao: 7.5,
    notaMesa: 8,
    notaProcedimentos: null,
    videoUrl: "#",
    videoNome: "diego-gp-15052026.mp4",
  },
  {
    id: "7",
    data: "12/06/2026",
    time: "shuffler",
    avaliadoNome: "Marcos Vieira",
    avaliadorNome: "Carlos Mendes",
    status: "em_analise",
    tipoAvaliacao: "performance_coach",
    turno: "Noite",
    estudioId: "sports_club",
    jogo: null,
    mesaId: null,
    pontosFortes: null,
    pontosDesenvolver: null,
    notaTotal: 7.8,
    notaImagem: 7.5,
    notaComunicacao: 8,
    notaMesa: null,
    notaProcedimentos: 7.9,
    videoUrl: "#",
    videoNome: "marcos-12062026.mp4",
  },
];

export const PERFORMANCE_HUB_AGENDA_MOCK: PerformanceHubAgendaItem[] = [
  {
    id: "a1",
    time: "game_presenter",
    nome: "Fernando Rocha",
    goLive: "12/03/2026",
    turno: "Manhã",
    realizadas: 3,
    pendentes: 1,
  },
  {
    id: "a2",
    time: "game_presenter",
    nome: "Camila Duarte",
    goLive: "22/01/2026",
    turno: "Tarde",
    realizadas: 5,
    pendentes: 2,
  },
  {
    id: "a3",
    time: "game_presenter",
    nome: "Bruno Nakamura",
    goLive: "05/06/2026",
    turno: "Noite",
    realizadas: 1,
    pendentes: 1,
  },
  {
    id: "a4",
    time: "shuffler",
    nome: "Diego Santana",
    goLive: "08/02/2026",
    turno: "Tarde",
    realizadas: 2,
    pendentes: 1,
  },
];
