import type { CsChamadoRow } from "../types/csAtendimento";

/**
 * Preview de layout da aba E-mail — removido quando a ingestão Outlook estiver ativa.
 * IDs prefixados com `mock-email-` para não chamar RPC de atendimento.
 */
export const CS_ATENDIMENTO_EMAIL_LAYOUT_MOCK_ATIVO = true;

export const CS_ATENDIMENTO_EMAIL_MOCK_ROWS: CsChamadoRow[] = [
  {
    id: "mock-email-001",
    protocolo: "EMAIL-2026/0001",
    origem: "email",
    status: "aberto",
    nome_completo: "contato@parceiro.com.br",
    telefone: null,
    email: "contato@parceiro.com.br",
    atuacao: "outros",
    empresa: null,
    mensagem:
      "Bom dia,\n\nGostaríamos de agendar uma call para discutir a integração das mesas dedicadas.\n\nAtt,\nEquipe Comercial",
    assunto: "Integração de mesas dedicadas",
    inicio_atendimento_em: null,
    arquivado_em: null,
    atendente_id: null,
    created_at: "2026-07-08T09:14:00.000Z",
    updated_at: "2026-07-08T09:14:00.000Z",
    atendente: null,
  },
  {
    id: "mock-email-002",
    protocolo: "EMAIL-2026/0002",
    origem: "email",
    status: "aberto",
    nome_completo: "suporte@operadoraexemplo.com",
    telefone: null,
    email: "suporte@operadoraexemplo.com",
    atuacao: "outros",
    empresa: null,
    mensagem: "Prezados, identificamos instabilidade no sinal da mesa Blackjack 1 ontem à noite. Podem verificar?",
    assunto: "Instabilidade no sinal — Blackjack 1",
    inicio_atendimento_em: null,
    arquivado_em: null,
    atendente_id: null,
    created_at: "2026-07-08T11:42:00.000Z",
    updated_at: "2026-07-08T11:42:00.000Z",
    atendente: null,
  },
  {
    id: "mock-email-003",
    protocolo: "EMAIL-2026/0003",
    origem: "email",
    status: "em_andamento",
    nome_completo: "ricardo.mendes@provedor.io",
    telefone: null,
    email: "ricardo.mendes@provedor.io",
    atuacao: "outros",
    empresa: null,
    mensagem: "Olá, precisamos do relatório de UAP da última semana para reconciliação interna.",
    assunto: "Solicitação de relatório UAP",
    inicio_atendimento_em: "2026-07-07T15:20:00.000Z",
    arquivado_em: null,
    atendente_id: "mock-profile-cs-01",
    created_at: "2026-07-07T14:05:00.000Z",
    updated_at: "2026-07-07T15:20:00.000Z",
    atendente: { id: "mock-profile-cs-01", name: "Ana Paula Ribeiro" },
  },
  {
    id: "mock-email-004",
    protocolo: "EMAIL-2026/0004",
    origem: "email",
    status: "em_andamento",
    nome_completo: "jogador.exemplo@gmail.com",
    telefone: null,
    email: "jogador.exemplo@gmail.com",
    atuacao: "outros",
    empresa: null,
    mensagem: "Não consigo acessar a mesa de Roleta na operadora. O chat da casa me direcionou para vocês.",
    assunto: "Dúvida sobre acesso à mesa de Roleta",
    inicio_atendimento_em: "2026-07-08T08:30:00.000Z",
    arquivado_em: null,
    atendente_id: "mock-profile-cs-02",
    created_at: "2026-07-08T07:55:00.000Z",
    updated_at: "2026-07-08T08:30:00.000Z",
    atendente: { id: "mock-profile-cs-02", name: "Felipe Saturnino" },
  },
  {
    id: "mock-email-005",
    protocolo: "EMAIL-2026/0005",
    origem: "email",
    status: "arquivado",
    nome_completo: "financeiro@casaapostas.com",
    telefone: null,
    email: "financeiro@casaapostas.com",
    atuacao: "outros",
    empresa: null,
    mensagem: "Segue anexo a planilha de conferência do fechamento de junho. Aguardamos retorno.",
    assunto: "Fechamento financeiro — junho/2026",
    inicio_atendimento_em: "2026-07-05T10:00:00.000Z",
    arquivado_em: "2026-07-06T16:45:00.000Z",
    atendente_id: "mock-profile-cs-01",
    created_at: "2026-07-05T09:12:00.000Z",
    updated_at: "2026-07-06T16:45:00.000Z",
    atendente: { id: "mock-profile-cs-01", name: "Ana Paula Ribeiro" },
  },
  {
    id: "mock-email-006",
    protocolo: "EMAIL-2026/0006",
    origem: "email",
    status: "arquivado",
    nome_completo: "ti@agregador.net",
    telefone: null,
    email: "ti@agregador.net",
    atuacao: "outros",
    empresa: null,
    mensagem: "Confirmamos que o ambiente de homologação foi liberado. Podemos seguir com os testes?",
    assunto: "Homologação — ambiente liberado",
    inicio_atendimento_em: "2026-07-03T11:15:00.000Z",
    arquivado_em: "2026-07-04T09:00:00.000Z",
    atendente_id: "mock-profile-cs-02",
    created_at: "2026-07-03T10:40:00.000Z",
    updated_at: "2026-07-04T09:00:00.000Z",
    atendente: { id: "mock-profile-cs-02", name: "Felipe Saturnino" },
  },
];

export function isCsChamadoEmailLayoutMock(id: string): boolean {
  return id.startsWith("mock-email-");
}
