/** @deprecated Importar de `../shared/homeSharedUi` */
export {
  HOME_SECTION_TITLE as HOME_INVESTIDOR_SECTION_TITLE,
  homeSectionTitleStyle as homeInvestidorSectionTitleStyle,
  HOME_BODY_MUTED as HOME_INVESTIDOR_BODY_MUTED,
  HOME_KPI_BREAKDOWN_LIST as HOME_INVESTIDOR_OPERADORA_LIST,
  HOME_KPI_BREAKDOWN_ROW as HOME_INVESTIDOR_OPERADORA_ROW,
  HOME_LINK_BUTTON as HOME_INVESTIDOR_LINK_BUTTON,
  HOME_FOOTER_HINT as HOME_INVESTIDOR_FOOTER_HINT,
} from "../shared/homeSharedUi";
